/**
 * Massive Medicine Data Library (Clinical Grade)
 * Includes Generics, Common Brands, Strengths, and Formulations.
 */
export const medicineData = [
    // --- ANALGESICS & ANTI-INFLAMMATORY ---
    "Paracetamol 500mg (Tablet)",
    "Paracetamol 1g (Tablet)",
    "Paracetamol 125mg/5ml (Syrup)",
    "Paracetamol 250mg/5ml (Syrup)",
    "Paracetamol 1g/100ml (IV Infusion)",
    "Paracetamol 125mg (Suppository)",
    "Paracetamol 250mg (Suppository)",
    "Ibuprofen 200mg (Tablet)",
    "Ibuprofen 400mg (Tablet)",
    "Ibuprofen 600mg (Tablet)",
    "Ibuprofen 100mg/5ml (Suspension)",
    "Diclofenac Sodium 50mg (Tablet)",
    "Diclofenac Sodium 100mg (SR Tablet)",
    "Diclofenac Potassium 50mg (Cataflam)",
    "Diclofenac 75mg/3ml (Injection)",
    "Diclofenac 1% (Gel)",
    "Aceclofenac 100mg (Tablet)",
    "Aspirin 75mg (Low Dose)",
    "Aspirin 300mg (Tablet)",
    "Celecoxib 100mg (Celebrex)",
    "Celecoxib 200mg (Celebrex)",
    "Etoricoxib 60mg (Arcoxia)",
    "Etoricoxib 90mg (Arcoxia)",
    "Etoricoxib 120mg (Arcoxia)",
    "Naproxen 250mg (Tablet)",
    "Naproxen 500mg (Tablet)",
    "Tramadol 50mg (Capsule)",
    "Tramadol 100mg (SR Tablet)",
    "Tramadol 50mg/ml (Injection)",
    "Tramadol 100mg/2ml (Injection)",
    "Morphine 10mg (Tablet)",
    "Morphine 10mg/ml (Injection)",
    "Pethidine 50mg/ml (Injection)",
    "Fentanyl 50mcg/ml (Injection)",
    "Fentanyl 25mcg/hr (Patch)",
    "Ketorolac 30mg/ml (Injection)",

    // --- ANTIBIOTICS ---
    "Amoxicillin 250mg (Capsule)",
    "Amoxicillin 500mg (Capsule)",
    "Amoxicillin 125mg/5ml (Suspension)",
    "Amoxicillin 250mg/5ml (Suspension)",
    "Amoxicillin 625mg (Augmentin/Amox-Clav)",
    "Amoxicillin 1g (Augmentin/Amox-Clav)",
    "Amoxicillin 1.2g (Augmentin Injection)",
    "Ampicillin 500mg (Injection)",
    "Ampicillin 1g (Injection)",
    "Ampiclox 500mg (Ampicillin/Cloxacillin)",
    "Ampiclox 250mg (Suspension)",
    "Ciprofloxacin 250mg (Tablet)",
    "Ciprofloxacin 500mg (Tablet)",
    "Ciprofloxacin 750mg (Tablet)",
    "Ciprofloxacin 200mg/100ml (IV)",
    "Ciprofloxacin 0.3% (Eye/Ear Drops)",
    "Azithromycin 250mg (Tablet)",
    "Azithromycin 500mg (Tablet)",
    "Azithromycin 200mg/5ml (Suspension)",
    "Erythromycin 250mg (Tablet)",
    "Erythromycin 500mg (Tablet)",
    "Erythromycin 125mg/5ml (Suspension)",
    "Clarithromycin 500mg (Tablet)",
    "Clarithromycin 125mg/5ml (Suspension)",
    "Ceftriaxone 250mg (Injection)",
    "Ceftriaxone 500mg (Injection)",
    "Ceftriaxone 1g (Injection/Rocephin)",
    "Ceftriaxone 2g (Injection)",
    "Cefuroxime 250mg (Zinnat)",
    "Cefuroxime 500mg (Zinnat)",
    "Cefuroxime 125mg/5ml (Suspension)",
    "Cefuroxime 750mg (Injection)",
    "Cefuroxime 1.5g (Injection)",
    "Cefixime 200mg (Tablet)",
    "Cefixime 400mg (Tablet)",
    "Cefixime 100mg/5ml (Suspension)",
    "Ceftazidime 1g (Injection)",
    "Cefotaxime 1g (Injection)",
    "Cefalexin 500mg (Capsule)",
    "Doxycycline 100mg (Capsule)",
    "Metronidazole 200mg (Tablet)",
    "Metronidazole 400mg (Flagyl)",
    "Metronidazole 200mg/5ml (Suspension)",
    "Metronidazole 500mg/100ml (IV)",
    "Nitrofurantoin 50mg (Tablet)",
    "Nitrofurantoin 100mg (Macrodantin)",
    "Nitrofurantoin 25mg/5ml (Suspension)",
    "Gentamicin 80mg/2ml (Injection)",
    "Gentamicin 20mg/2ml (Pediatric Injection)",
    "Gentamicin 0.3% (Eye/Ear Drops)",
    "Levofloxacin 500mg (Tablet)",
    "Levofloxacin 750mg (Tablet)",
    "Levofloxacin 500mg/100ml (IV)",
    "Meropenem 500mg (Injection)",
    "Meropenem 1g (Injection)",
    "Imipenem/Cilastatin 500mg (Injection)",
    "Vancomycin 500mg (Injection)",
    "Vancomycin 1g (Injection)",
    "Linezolid 600mg (Tablet)",
    "Linezolid 2mg/ml (IV)",
    "Chloramphenicol 250mg (Capsule)",
    "Chloramphenicol 1g (Injection)",
    "Chloramphenicol 0.5% (Eye Drops)",
    "Sulfamethoxazole/Trimethoprim 480mg (Septrin)",
    "Sulfamethoxazole/Trimethoprim 960mg (Septrin DS)",
    "Sulfamethoxazole/Trimethoprim 240mg/5ml (Suspension)",

    // --- ANTIFUNGALS ---
    "Fluconazole 50mg (Capsule)",
    "Fluconazole 150mg (Diflucan)",
    "Fluconazole 200mg (Capsule)",
    "Fluconazole 2mg/ml (IV)",
    "Ketoconazole 200mg (Tablet)",
    "Ketoconazole 2% (Cream)",
    "Ketoconazole 2% (Shampoo)",
    "Griseofulvin 125mg (Tablet)",
    "Griseofulvin 500mg (Tablet)",
    "Nystatin 100,000 units (Oral Drops)",
    "Nystatin 100,000 units (Pessary)",
    "Clotrimazole 1% (Cream)",
    "Clotrimazole 100mg (Pessary)",
    "Clotrimazole 500mg (Pessary)",
    "Terbinafine 250mg (Tablet)",
    "Amphotericin B 50mg (Injection)",
    "Itraconazole 100mg (Capsule)",
    "Voriconazole 200mg (Tablet)",

    // --- ANTIVIRALS ---
    "Aciclovir 200mg (Tablet)",
    "Aciclovir 400mg (Tablet)",
    "Aciclovir 800mg (Tablet)",
    "Aciclovir 250mg (Injection)",
    "Aciclovir 3% (Eye Ointment)",
    "Aciclovir 5% (Cream)",
    "Valaciclovir 500mg (Tablet)",
    "Tenofovir 300mg (Tablet)",
    "Lamivudine 150mg (Tablet)",
    "Lamivudine 300mg (Tablet)",
    "Efavirenz 600mg (Tablet)",
    "Dolutegravir 50mg (Tablet)",
    "Tenofovir/Lamivudine/Dolutegravir (TLD Tablet)",
    "Nevirapine 200mg (Tablet)",
    "Zidovudine 300mg (Tablet)",
    "Oseltamivir 75mg (Tamiflu)",
    "Sofosbuvir 400mg (Tablet)",
    "Daclatasvir 60mg (Tablet)",

    // --- ANTIMALARIALS ---
    "Artemether 20mg / Lumefantrine 120mg (Coartem 1x6)",
    "Artemether 20mg / Lumefantrine 120mg (Coartem 2x6)",
    "Artemether 20mg / Lumefantrine 120mg (Coartem 3x6)",
    "Artemether 20mg / Lumefantrine 120mg (Coartem 4x6)",
    "Artemether 80mg / Lumefantrine 480mg (Tablet)",
    "Artemether/Lumefantrine (Suspension)",
    "Artesunate 60mg (Injection)",
    "Artesunate 120mg (Injection)",
    "Quinine Sulfate 300mg (Tablet)",
    "Quinine Dihydrochloride 300mg/ml (Injection)",
    "Sulfadoxine/Pyrimethamine 500/25mg (Fansidar)",
    "Dihydroartemisinin/Piperaquine (P-Alaxin)",
    "Artemether 80mg/ml (Injection)",
    "Chloroquine 150mg (Tablet)",

    // --- ANTIHYPERTENSIVES ---
    "Amlodipine 5mg (Tablet)",
    "Amlodipine 10mg (Tablet)",
    "Lisinopril 5mg (Tablet)",
    "Lisinopril 10mg (Zestril)",
    "Lisinopril 20mg (Tablet)",
    "Enalapril 5mg (Tablet)",
    "Enalapril 10mg (Tablet)",
    "Ramipril 2.5mg (Tablet)",
    "Ramipril 5mg (Tablet)",
    "Ramipril 10mg (Tablet)",
    "Losartan 50mg (Cozaar)",
    "Losartan 100mg (Tablet)",
    "Valsartan 80mg (Tablet)",
    "Valsartan 160mg (Tablet)",
    "Telmisartan 40mg (Micardis)",
    "Telmisartan 80mg (Micardis)",
    "Atenolol 50mg (Tablet)",
    "Atenolol 100mg (Tablet)",
    "Propranolol 10mg (Tablet)",
    "Propranolol 40mg (Tablet)",
    "Bisoprolol 2.5mg (Tablet)",
    "Bisoprolol 5mg (Concor)",
    "Bisoprolol 10mg (Tablet)",
    "Carvedilol 6.25mg (Tablet)",
    "Carvedilol 12.5mg (Tablet)",
    "Carvedilol 25mg (Tablet)",
    "Methyldopa 250mg (Aldomet)",
    "Methyldopa 500mg (Tablet)",
    "Hydralazine 25mg (Tablet)",
    "Hydralazine 20mg (Injection)",
    "Nifedipine 20mg (Retard Tablet)",
    "Nifedipine 30mg (Adalat LA)",
    "Nifedipine 60mg (Adalat LA)",
    "Verapamil 40mg (Tablet)",
    "Verapamil 80mg (Tablet)",
    "Diltiazem 60mg (Tablet)",
    "Spironolactone 25mg (Aldactone)",
    "Spironolactone 50mg (Tablet)",
    "Hydrochlorothiazide 12.5mg (Tablet)",
    "Hydrochlorothiazide 25mg (Tablet)",
    "Furosemide 20mg (Lasix)",
    "Furosemide 40mg (Lasix)",
    "Furosemide 20mg/2ml (Injection)",
    "Labetalol 100mg (Tablet)",
    "Labetalol 5mg/ml (Injection)",

    // --- ANTIDIABETICS ---
    "Metformin 500mg (Glucophage)",
    "Metformin 850mg (Tablet)",
    "Metformin 1000mg (Tablet)",
    "Metformin 500mg (SR Tablet)",
    "Metformin 1000mg (SR Tablet)",
    "Glibenclamide 5mg (Daonil)",
    "Gliclazide 30mg (Diamicron MR)",
    "Gliclazide 60mg (Diamicron MR)",
    "Gliclazide 80mg (Tablet)",
    "Glimepiride 1mg (Amaryl)",
    "Glimepiride 2mg (Amaryl)",
    "Glimepiride 4mg (Amaryl)",
    "Pioglitazone 15mg (Tablet)",
    "Pioglitazone 30mg (Tablet)",
    "Sitagliptin 50mg (Januvia)",
    "Sitagliptin 100mg (Januvia)",
    "Vildagliptin 50mg (Galvus)",
    "Dapagliflozin 5mg (Forxiga)",
    "Dapagliflozin 10mg (Forxiga)",
    "Empagliflozin 10mg (Jardiance)",
    "Insulin Soluble (Regular/Humulin R) 100IU/ml",
    "Insulin Isophane (NPH/Humulin N) 100IU/ml",
    "Insulin Biphasic (Mixtard 30/70) 100IU/ml",
    "Insulin Glargine (Lantus) 100IU/ml",
    "Insulin Aspart (NovoRapid) 100IU/ml",

    // --- STATINS & LIPID LOWERING ---
    "Atorvastatin 10mg (Lipitor)",
    "Atorvastatin 20mg (Lipitor)",
    "Atorvastatin 40mg (Lipitor)",
    "Atorvastatin 80mg (Lipitor)",
    "Rosuvastatin 5mg (Crestor)",
    "Rosuvastatin 10mg (Crestor)",
    "Rosuvastatin 20mg (Crestor)",
    "Simvastatin 10mg (Zocor)",
    "Simvastatin 20mg (Zocor)",
    "Simvastatin 40mg (Tablet)",

    // --- GASTROINTESTINAL ---
    "Omeprazole 20mg (Capsule)",
    "Omeprazole 40mg (Capsule)",
    "Omeprazole 40mg (Injection)",
    "Esomeprazole 20mg (Nexium)",
    "Esomeprazole 40mg (Nexium)",
    "Esomeprazole 40mg (Injection)",
    "Pantoprazole 40mg (Tablet)",
    "Pantoprazole 40mg (Injection)",
    "Rabeprazole 20mg (Tablet)",
    "Ranitidine 150mg (Zantac)",
    "Ranitidine 300mg (Tablet)",
    "Ranitidine 50mg/2ml (Injection)",
    "Famotidine 20mg (Tablet)",
    "Magnesium Trisilicate (Antacid Suspension)",
    "Magnesium Trisilicate (Antacid Tablet)",
    "Gaviscon (Suspension)",
    "Gaviscon (Advance Liquid)",
    "Hyoscine Butylbromide 10mg (Buscopan)",
    "Hyoscine Butylbromide 20mg/ml (Injection)",
    "Metoclopramide 10mg (Tablet)",
    "Metoclopramide 10mg/2ml (Injection)",
    "Domperidone 10mg (Tablet)",
    "Domperidone 1mg/ml (Suspension)",
    "Ondansetron 4mg (Zofran)",
    "Ondansetron 8mg (Zofran)",
    "Ondansetron 4mg/2ml (Injection)",
    "Ondansetron 8mg/4ml (Injection)",
    "Loperamide 2mg (Imodium)",
    "Oral Rehydration Salts (ORS Sachet)",
    "Zinc Sulfate 20mg (Tablet)",
    "Bisacodyl 5mg (Dulcolax Tablet)",
    "Bisacodyl 10mg (Suppository)",
    "Lactulose 3.3g/5ml (Syrup)",
    "Senna (Tablet)",

    // --- RESPIRATORY ---
    "Salbutamol 100mcg (Ventolin Inhaler)",
    "Salbutamol 2mg (Tablet)",
    "Salbutamol 4mg (Tablet)",
    "Salbutamol 2mg/5ml (Syrup)",
    "Salbutamol 2.5mg/2.5ml (Nebulizer Solution)",
    "Salbutamol 5mg/ml (Nebulizer Solution)",
    "Beclometasone 50mcg (Inhaler)",
    "Beclometasone 100mcg (Inhaler)",
    "Beclometasone 250mcg (Inhaler)",
    "Fluticasone/Salmeterol 125/25 (Seretide)",
    "Fluticasone/Salmeterol 250/25 (Seretide)",
    "Budesonide 200mcg (Pulmicort Inhaler)",
    "Ipratropium Bromide 20mcg (Inhaler)",
    "Ipratropium Bromide 250mcg/ml (Nebulizer)",
    "Prednisolone 5mg (Tablet)",
    "Prednisolone 25mg (Tablet)",
    "Dexamethasone 0.5mg (Tablet)",
    "Dexamethasone 4mg (Tablet)",
    "Dexamethasone 4mg/ml (Injection)",
    "Hydrocortisone 100mg (Injection)",
    "Aminophylline 250mg/10ml (Injection)",
    "Montelukast 5mg (Singulair Chewable)",
    "Montelukast 10mg (Singulair)",
    "Cetirizine 10mg (Zyrtec)",
    "Loratadine 10mg (Claritin)",
    "Chlorphenamine 4mg (Piriton)",
    "Chlorphenamine 10mg/ml (Injection)",
    "Promethazine 25mg (Avomine)",
    "Promethazine 5mg/5ml (Elixir)",
    "Diphenhydramine (Benadryl Syrup)",

    // --- PSYCHIATRY & NEUROLOGY ---
    "Diazepam 2mg (Tablet)",
    "Diazepam 5mg (Valium)",
    "Diazepam 10mg (Tablet)",
    "Diazepam 10mg/2ml (Injection)",
    "Lorazepam 1mg (Ativan)",
    "Lorazepam 2mg (Tablet)",
    "Alprazolam 0.5mg (Xanax)",
    "Alprazolam 1mg (Xanax)",
    "Clonazepam 0.5mg (Tablet)",
    "Clonazepam 2mg (Rivotril)",
    "Haloperidol 1.5mg (Tablet)",
    "Haloperidol 5mg (Tablet)",
    "Haloperidol 5mg/ml (Injection)",
    "Haloperidol 50mg/ml (Decanoate Injection)",
    "Chlorpromazine 25mg (Largactil)",
    "Chlorpromazine 100mg (Tablet)",
    "Chlorpromazine 50mg/2ml (Injection)",
    "Olanzapine 5mg (Zyprexa)",
    "Olanzapine 10mg (Zyprexa)",
    "Risperidone 1mg (Risperdal)",
    "Risperidone 2mg (Risperdal)",
    "Quetiapine 25mg (Seroquel)",
    "Quetiapine 100mg (Seroquel)",
    "Amitriptyline 10mg (Tablet)",
    "Amitriptyline 25mg (Tablet)",
    "Fluoxetine 20mg (Prozac)",
    "Sertraline 50mg (Zoloft)",
    "Escitalopram 10mg (Cipralex)",
    "Carbamazepine 200mg (Tegretol)",
    "Carbamazepine 400mg (Tegretol)",
    "Sodium Valproate 200mg (Epilim)",
    "Sodium Valproate 500mg (Epilim Chrono)",
    "Phenytoin 100mg (Epanutin)",
    "Phenobarbital 30mg (Tablet)",
    "Phenobarbital 60mg (Tablet)",
    "Levetiracetam 500mg (Keppra)",
    "Levodopa 100mg / Carbidopa 25mg (Sinemet)",

    // --- VITAMINS & SUPPLEMENTS ---
    "Vitamin B-Complex (Tablet)",
    "Vitamin B-Complex (Injection)",
    "Vitamin B1 (Thiamine) 100mg (Tablet)",
    "Vitamin B6 (Pyridoxine) 50mg (Tablet)",
    "Vitamin B12 (Cyanocobalamin) 1000mcg (Injection)",
    "Vitamin C (Ascorbic Acid) 100mg (Tablet)",
    "Vitamin C (Ascorbic Acid) 500mg (Tablet)",
    "Vitamin D3 1000IU (Tablet)",
    "Vitamin D3 60,000IU (Capsule)",
    "Folic Acid 1mg (Tablet)",
    "Folic Acid 5mg (Tablet)",
    "Ferrous Sulfate 200mg (Tablet)",
    "Ferrous Gluconate 300mg (Tablet)",
    "Ferrous Sulfate + Folic Acid (Fefol)",
    "Calcium Carbonate 500mg (Tablet)",
    "Calcium + Vitamin D3 (Tablet)",
    "Multivitamin (Syrup)",
    "Multivitamin (Capsule)",

    // --- IV FLUIDS ---
    "Normal Saline 0.9% (500ml)",
    "Normal Saline 0.9% (1000ml)",
    "Dextrose 5% (500ml)",
    "Dextrose 10% (500ml)",
    "Dextrose 50% (50ml Injection)",
    "Dextrose Saline 5%/0.9% (500ml)",
    "Half-Normal Dextrose Saline 5%/0.45% (500ml)",
    "Ringer's Lactate (500ml)",
    "Ringer's Lactate (1000ml)",
    "Mannitol 20% (250ml)",
    "Sodium Bicarbonate 8.4% (100ml)",
    "Metronidazole 500mg/100ml (IV Infusion)",

    // --- TOPICAL & MISC ---
    "Mupirocin 2% (Bactroban Ointment)",
    "Silver Sulfadiazine 1% (Flamazine Cream)",
    "Hydrocortisone 1% (Cream)",
    "Betamethasone 0.1% (Cream)",
    "Gentamicin 0.1% (Cream)",
    "Lidocaine 2% (Jelly)",
    "Lidocaine 5% (Ointment)",
    "Lidocaine/Prilocaine (EMLA Cream)",
    "Permethrin 5% (Lotion)",
    "Calamine (Lotion)",
    "Timolol 0.5% (Eye Drops)",
    "Latanoprost 0.005% (Xalatan Eye Drops)",
    "Atropine 1% (Eye Drops)",
    "Hypromellose (Artificial Tears)",
    "Ciprofloxacin 0.3% (Eye/Ear Drops)",
    "Ofloxacin 0.3% (Eye/Ear Drops)",
    "Sodium Chloride 0.9% (Nasal Spray)",
    "Oxymetazoline 0.05% (Nasal Spray)",

    // --- HORMONES & OTHERS ---
    "Levothyroxine 50mcg (Tablet)",
    "Levothyroxine 100mcg (Eltroxin)",
    "Carbimazole 5mg (Tablet)",
    "Dexamethasone 4mg/ml (Injection)",
    "Hydrocortisone 100mg (Injection)",
    "Methylprednisolone 40mg (Depo-Medrol)",
    "Oxytocin 10IU (Injection)",
    "Misoprostol 200mcg (Cytotec)",
    "Medroxyprogesterone 150mg (Depo-Provera)",
    "Levonorgestrel 1.5mg (Postinor-2/Escapelle)",
    "Combined Oral Contraceptive (Microgynon)",
    "Warfarin 1mg (Tablet)",
    "Warfarin 2mg (Tablet)",
    "Warfarin 5mg (Tablet)",
    "Heparin 5000IU/ml (Injection)",
    "Enoxaparin 40mg (Clexane)",
    "Enoxaparin 60mg (Clexane)",
    "Clopidogrel 75mg (Plavix)",
    "Phytomenadione (Vitamin K) 10mg/ml (Injection)",
    "Tranexamic Acid 500mg (Tablet)",
    "Tranexamic Acid 500mg/5ml (Injection)",
    "Sildenafil 50mg (Viagra)",
    "Sildenafil 100mg (Viagra)",
    "Tamsulosin 0.4mg (Flomax)",
    "Finasteride 5mg (Tablet)",
];
